name: print text when java file is modified
on:
  push:
    paths:
      - '**.java'
  pull_request:
    paths:
      - '**.java'
  workflow_dispatch:
jobs:
  job:
    runs-on: ubuntu-latest
    name: print when java file is added modified
      - run: echo 'IT WORKS. Java file was modified/added'
