name: Build docker image and push to heroku
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '15.0.1'
      - name: build Jar
        run: ./back/gradlew build
      - name: build image and push to heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_SERVER_API_KEY }}
          heroku_app_name: lagalt-server
          heroku_email: ${{ secrets.HEROKU_SERVER_EMAIL }}
          usedocker: true
          appdir: ./back
          healthcheck: https://lagalt-server.herokuapp.com/api/v1/health


        # https://github.com/marketplace/actions/build-push-and-release-a-docker-container-to-heroku
#        - name: Build, Push and Release to Heroku.
#        uses: gonuit/heroku-docker-deploy@v1.3.2
#          with:
#          email: ${{ secrets.HEROKU_SERVER_EMAIL }}
#          heroku_api_key: ${{ secrets.HEROKU_SERVER_API_KEY }}
#          heroku_app_name: lagalt-server
#          dockerfile_directory: ./
#          dockerfile_name: Dockerfile
#          docker_options: "--no-cache"
#        process_type: web
