name: Build docker image and push to heroku
on:
  workflow_dispatch:

jobs:
  job:
    name: buildJar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
      - run: ./back/gradlew build
      - uses: actions/upload-artifact@v2
        with:
          name lagalt-0.0.1-SNAPSHOT.jar
          path: ./back/build/libs
  # https://github.com/marketplace/actions/build-push-and-release-a-docker-container-to-heroku
  build:
    needs: buildJar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.2
        with:
          email: ${{ secrets.HEROKU_SERVER_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_SERVER_API_KEY }}
          heroku_app_name: lagalt-server
          dockerfile_directory: ./back
          dockerfile_name: Dockerfile
          docker_options: "--no-cache"
          process_type: web
